# Generated by Django 2.1.1 on 2018-10-09 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('name_cn', models.CharField(max_length=30)),
                ('gender', models.IntegerField(choices=[(0, 'female'), (1, 'male')])),
                ('describe', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('name_cn', models.CharField(max_length=30)),
                ('weapon', models.CharField(blank=True, max_length=30, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CharacterAction', to='resource.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.IntegerField(choices=[(0, 'female'), (1, 'male'), (2, 'either')])),
                ('name_cn', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('name_cn', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='WAS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=30)),
                ('direction_num', models.IntegerField(default=1)),
                ('frame_num', models.IntegerField(default=1)),
                ('hooked', models.BooleanField(default=False)),
                ('describe', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='WDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='was',
            name='wdf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WAS', to='resource.WDF'),
        ),
        migrations.AddField(
            model_name='faction',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Faction', to='resource.Race'),
        ),
        migrations.AddField(
            model_name='characteraction',
            name='was',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CharacterAction', to='resource.WAS'),
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Character', to='resource.Race'),
        ),
    ]
