# Generated by Django 2.1.1 on 2018-10-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='reborn',
            field=models.IntegerField(choices=[(0, '未转形象'), (1, '一转形象'), (3, '三转形象')], default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.IntegerField(choices=[(-1, 'female'), (1, 'male')]),
        ),
        migrations.AlterField(
            model_name='faction',
            name='gender',
            field=models.IntegerField(choices=[(-1, 'female'), (1, 'male'), (0, 'either')]),
        ),
    ]
