# Generated by Django 2.1.1 on 2018-10-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_auto_20181009_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteraction',
            name='name_cn',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
