# Generated by Django 2.1.1 on 2018-10-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0005_skill_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='feature',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
