# Generated by Django 2.1.1 on 2018-10-11 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0006_faction_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('name_cn', models.CharField(max_length=30)),
                ('type', models.IntegerField(choices=[(0, '普通召唤兽'), (10, '畜牧召唤兽'), (20, '新召唤兽'), (30, '天书召唤兽'), (40, '高级守护'), (50, '龙涎丸召唤兽'), (99, '神兽')], default=0)),
                ('title_level', models.IntegerField(default=0)),
                ('init_max_hp', models.FloatField(default=0.0)),
                ('init_max_mp', models.FloatField(default=0.0)),
                ('init_max_ap', models.FloatField(default=0.0)),
                ('init_max_sp', models.FloatField(default=0.0)),
                ('init_max_speed', models.FloatField(default=0.0)),
                ('init_max_growth', models.FloatField(default=0.0)),
                ('init_max_high_growth', models.FloatField(default=0.0)),
                ('gold', models.FloatField(default=0.0)),
                ('wood', models.FloatField(default=0.0)),
                ('soil', models.FloatField(default=0.0)),
                ('water', models.FloatField(default=0.0)),
                ('fire', models.FloatField(default=0.0)),
                ('describe', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='MonsterAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('name_cn', models.CharField(blank=True, max_length=30, null=True)),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MonsterAction', to='resource.Monster')),
                ('was', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MonsterAction', to='resource.WAS')),
            ],
        ),
        migrations.CreateModel(
            name='MonsterAndSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MonsterAndSkill', to='resource.Monster')),
            ],
        ),
        migrations.CreateModel(
            name='MonsterSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('name_cn', models.CharField(max_length=30)),
                ('nick_name', models.CharField(max_length=30)),
                ('level', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='monsterandskill',
            name='monster_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MonsterAndSkill', to='resource.MonsterSkill'),
        ),
    ]
