# Generated by Django 2.1.1 on 2018-10-11 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0007_auto_20181011_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='describe',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
