# Generated by Django 2.1.1 on 2018-10-12 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0010_remove_monsterandskill_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('name_cn', models.CharField(max_length=30)),
                ('was', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Effect', to='resource.WAS')),
            ],
        ),
        migrations.AddField(
            model_name='monsterskill',
            name='effect',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='MonsterSkill', to='resource.Effect'),
            preserve_default=False,
        ),
    ]
