# Generated by Django 2.1.1 on 2018-10-12 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0012_auto_20181012_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='effect',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Skill', to='resource.Effect'),
            preserve_default=False,
        ),
    ]
