# Generated by Django 2.1.1 on 2018-10-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0013_skill_effect'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='prototype',
            field=models.IntegerField(default=0),
        ),
    ]
