# Generated by Django 2.1.1 on 2018-10-16 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0014_monster_prototype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('name_cn', models.CharField(max_length=30)),
                ('describe', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ShapeAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('name_cn', models.CharField(max_length=30)),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ShapeAction', to='resource.Shape')),
                ('was', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ShapeAction', to='resource.WAS')),
            ],
        ),
    ]
