# Generated by Django 2.1.1 on 2018-10-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0015_shape_shapeaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shape',
            name='describe',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='shapeaction',
            name='name_cn',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
