# Generated by Django 2.1.1 on 2018-10-16 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0016_auto_20181016_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymbolicAnimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('name_cn', models.CharField(max_length=30)),
                ('describe', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SymbolicAnimalAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('name_cn', models.CharField(blank=True, max_length=30, null=True)),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SymbolicAnimalAction', to='resource.SymbolicAnimal')),
                ('was', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SymbolicAnimalAction', to='resource.WAS')),
            ],
        ),
    ]
