# Generated by Django 2.1.1 on 2018-10-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0017_symbolicanimal_symbolicanimalaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='was',
            name='describe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
