# Generated by Django 2.1.1 on 2018-10-19 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0018_auto_20181019_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonsterSkin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('name_cn', models.CharField(max_length=30)),
                ('describe', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonsterSkinAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('name_cn', models.CharField(blank=True, max_length=30, null=True)),
                ('monster_skin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MonsterSkinAction', to='resource.MonsterSkin')),
                ('was', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MonsterSkinAction', to='resource.WAS')),
            ],
        ),
        migrations.AddField(
            model_name='monster',
            name='skin_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monsterskin',
            name='monster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MonsterSkin', to='resource.Monster'),
        ),
    ]
