# Generated by Django 2.1.1 on 2018-10-23 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0019_auto_20181019_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterMount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('name_cn', models.CharField(blank=True, max_length=30, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CharacterMount', to='resource.Character')),
                ('was', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CharacterMount', to='resource.WAS')),
            ],
        ),
    ]
