# Generated by Django 2.1.1 on 2018-10-23 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0020_charactermount'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapAni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('name_cn', models.CharField(max_length=30)),
                ('was', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MapAni', to='resource.WAS')),
            ],
        ),
    ]
