# Generated by Django 2.1.1 on 2018-10-23 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0022_charactermount_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, '一坐'), (2, '二坐'), (3, '三坐'), (4, '四坐'), (5, '五坐'), (6, '六坐'), (7, '七坐')])),
                ('name', models.CharField(max_length=30)),
                ('name_cn', models.CharField(blank=True, max_length=30, null=True)),
                ('describe', models.CharField(blank=True, max_length=300, null=True)),
                ('init_max_mp', models.IntegerField(default=0)),
                ('init_max_ap', models.IntegerField(default=0)),
                ('init_max_hp', models.IntegerField(default=0)),
                ('init_max_mp_reinforce', models.IntegerField(default=0)),
                ('init_max_ap_reinforce', models.IntegerField(default=0)),
                ('init_max_hp_reinforce', models.IntegerField(default=0)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Mount', to='resource.Race')),
            ],
        ),
        migrations.CreateModel(
            name='MountAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('name_cn', models.CharField(blank=True, max_length=30, null=True)),
                ('mount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MountAction', to='resource.Mount')),
                ('was', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MountAction', to='resource.WAS')),
            ],
        ),
    ]
