# Generated by Django 2.1.1 on 2018-10-23 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0024_mountaction_character'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charactermount',
            name='character',
        ),
        migrations.RemoveField(
            model_name='charactermount',
            name='was',
        ),
        migrations.DeleteModel(
            name='CharacterMount',
        ),
    ]
