# Generated by Django 2.1.1 on 2018-10-29 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0026_characterphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShapePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('name_cn', models.CharField(blank=True, max_length=30, null=True)),
                ('level', models.IntegerField(default=0)),
                ('w', models.IntegerField(default=0)),
                ('h', models.IntegerField(default=0)),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ShapePhoto', to='resource.Shape')),
                ('was', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ShapePhoto', to='resource.WAS')),
            ],
        ),
    ]
