# Generated by Django 2.1.2 on 2018-12-28 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0028_wdf_describe'),
    ]

    operations = [
        migrations.CreateModel(
            name='UI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('name_cn', models.CharField(max_length=30)),
                ('was', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UI', to='resource.WAS')),
            ],
        ),
    ]
