# Generated by Django 2.1.2 on 2019-03-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0030_weapon'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='version',
            field=models.IntegerField(choices=[(0, 'old'), (1, 'new')], default=0),
        ),
    ]
