# Generated by Django 2.1.1 on 2018-11-15 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0028_wdf_describe'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('map_id', models.CharField(max_length=200)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Character', to='base.Account')),
                ('res', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Character', to='resource.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('version', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NPC', to='base.Map')),
                ('res', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NPC', to='resource.Shape')),
            ],
        ),
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('target_map_id', models.CharField(max_length=200)),
                ('target_x', models.IntegerField(default=0)),
                ('target_y', models.IntegerField(default=0)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Portal', to='base.Map')),
                ('res', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Portal', to='resource.MapAni')),
            ],
        ),
    ]
