# Generated by Django 2.1.5 on 2019-01-24 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_announcement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='name',
            new_name='account',
        ),
        migrations.AddField(
            model_name='account',
            name='create_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
