# Generated by Django 2.1.2 on 2019-02-19 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20190218_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='character_num',
            new_name='role_num',
        ),
        migrations.RemoveField(
            model_name='role',
            name='map_id',
        ),
        migrations.AddField(
            model_name='role',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='role',
            name='map',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Role', to='base.Map'),
        ),
        migrations.AddField(
            model_name='role',
            name='reborn',
            field=models.IntegerField(choices=[(0, '未转'), (1, '一转'), (2, '二转'), (3, '三转')], default=0),
        ),
        migrations.AlterField(
            model_name='map',
            name='version',
            field=models.IntegerField(choices=[(0, 'scene/'), (1, 'newscene/')]),
        ),
        migrations.AlterField(
            model_name='role',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Role', to='base.Account'),
        ),
        migrations.AlterField(
            model_name='role',
            name='res',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Role', to='resource.Character'),
        ),
    ]
