# Generated by Django 2.1.2 on 2019-03-11 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20190219_2346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='res',
            new_name='character',
        ),
    ]
