# Generated by Django 2.1.5 on 2019-05-13 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20190510_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portal',
            name='target_map_id',
        ),
        migrations.AddField(
            model_name='portal',
            name='target_map',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='PrePortal', to='base.Map'),
            preserve_default=False,
        ),
    ]
