# Generated by Django 2.1.5 on 2019-06-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20190513_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='direction',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='npc',
            name='npc_type',
            field=models.IntegerField(choices=[(0, '其他'), (1, '传送')], default=0),
        ),
    ]
