# Generated by Django 2.1.5 on 2019-06-14 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20190614_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPCTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_x', models.IntegerField(default=0)),
                ('target_y', models.IntegerField(default=0)),
                ('npc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NPCTarget', to='base.NPC')),
                ('target_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NPCTarget', to='base.Map')),
            ],
        ),
    ]
